backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
local_backend: true
display_url: https://sportclimbs.uk
site_url: https://sportclimbs.uk
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
media_library:
  name: cloudinary
  config:
    cloud_name: sportclimbs
    api_key: 826617453858452
publish_mode: editorial_workflow
collections:
- name: "harpur-hill"
  label: "Harpur Hill"
  folder: "content/peak/buxton/harpur-hill"
  create: false
  editor:
    preview: true
  fields:
  - {label: "Page Title", name: "title", widget: "string"}
  - {label: "Link Title (only needed if the main title is too long for menus)", name: "linktitle", widget: "string", required: false}
  - {label: "Subtitle (used if a crag has a second aka name)", name: "subtitle", widget: "string", required: false}
  - {label: "Body", name: "body", widget: "markdown"}
- name: "peak"
  label: "Peak District"
  folder: "content/peak"
  create: true
  nested:
    depth: 100
  editor:
    preview: true
  fields:
  - {label: "Page Title", name: "title", widget: "string"}
  - {label: "Link Title (only needed if the main title is too long for menus)", name: "linktitle", widget: "string", required: false}
  - {label: "Subtitle (used if a crag has a second aka name)", name: "subtitle", widget: "string", required: false}
  - {label: "Body", name: "body", widget: "markdown"}
- name: "south-wales"
  label: "South Wales"
  folder: "content/south-wales"
  create: true
  nested:
    depth: 100
  editor:
    preview: true
  fields:
  - {label: "Page Title", name: "title", widget: "string"}
  - {label: "Link Title (only needed if the main title is too long for menus)", name: "linktitle", widget: "string", required: false}
  - {label: "Subtitle (used if a crag has a second aka name)", name: "subtitle", widget: "string", required: false}
  - {label: "Body", name: "body", widget: "markdown"}
- name: "notes"
  label: "Notes"
  folder: "content/notes"
  create: true
  editor:
    preview: true
  fields:
  - {label: "Page Title", name: "title", widget: "string"}
  - {label: "Link Title (only needed if the main title is too long for menus)", name: "linktitle", widget: "string", required: false}
  - {label: "Subtitle (used if a crag has a second aka name)", name: "subtitle", widget: "string", required: false}
  - {label: "Body", name: "body", widget: "markdown"}
