backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
display_url: https://test.sportclimbs.uk
site_url: https://test.sportclimbs.uk
logo_url: images/sportclimbs.svg
# media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
# public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
media_library:
  name: uploadcare
  config:
    publicKey: 8fd1a2c69b970e6ccb26
collections:
- name: "harpur-hill"
  label: "Harpur Hill"
  folder: "content/peak/buxton/harpur-hill"
  create: true
  editor:
    preview: true
  fields:
  - {label: "Page Title", name: "title", widget: "string"}
  - {label: "Link Title (only needed if the main title is too long for menus)", name: "linktitle", widget: "string", required: false}
  - {label: "Subtitle (used if a crag has a second aka name)", name: "subtitle", widget: "string", required: false}
  - {label: Date, name: date, widget: datetime, required: true}
  - {label: "Body", name: "body", widget: "markdown"}
- name: "matlock"
  label: "Matlock area"
  folder: "content/peak/matlock"
  create: true
  editor:
    preview: true
  fields:
  - {label: "Page Title", name: "title", widget: "string"}
  - {label: "Link Title (only needed if the main title is too long for menus)", name: "linktitle", widget: "string", required: false}
  - {label: "Subtitle (used if a crag has a second aka name)", name: "subtitle", widget: "string", required: false}
  - {label: Date, name: date, widget: datetime, required: true}
  - {label: "Body", name: "body", widget: "markdown"}
- name: "colehill"
  label: "Colehill Quarry"
  folder: "content/peak/matlock/colehill-quarry"
  create: true
  editor:
    preview: true
  fields:
  - {label: "Page Title", name: "title", widget: "string"}
  - {label: "Link Title (only needed if the main title is too long for menus)", name: "linktitle", widget: "string", required: false}
  - {label: "Subtitle (used if a crag has a second aka name)", name: "subtitle", widget: "string", required: false}
  - {label: Date, name: date, widget: datetime, required: true}
  - {label: "Body", name: "body", widget: "markdown"}
- name: "helicopter-quarry"
  label: Helicopter Quarry
  folder: "content/peak/matlock/helicopter-quarry"
  create: true
  editor:
    preview: true
  fields:
  - {label: "Page Title", name: "title", widget: "string"}
  - {label: "Link Title (only needed if the main title is too long for menus)", name: "linktitle", widget: "string", required: false}
  - {label: "Subtitle (used if a crag has a second aka name)", name: "subtitle", widget: "string", required: false}
  - {label: "Date and Time (Press now to update)", name: date, widget: "datetime", required: false}
  - {label: "Summary (Press now to update)", name: "summary", widget: "string", required: false}
  - {label: "Body", name: "body", widget: "markdown"}
- name: "notes"
  label: "Notes"
  folder: "content/notes"
  create: true
  fields:
    - label: "Page Title"
      name: "title"
      widget: "string"
    - label: Time and Date
      name: date
      widget: datetime
      description: Press the now button to change this date to today, right now
    - label: Summary (used in lists of updates)
      name: summary
      widget: "string"
      required: false
    - label: "Body"
      name: "body"
      widget: "markdown"
